theme = "dark_plus"

[editor]
cursorline = true
line-number = "relative"
rulers = [80, 120]
bufferline = "multiple"
true-color = true
color-modes = true
auto-completion = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.soft-wrap]
enable = true

